apiVersion: v1
data:
  day: friday
  special.type: charm
kind: ConfigMap
metadata:
  creationTimestamp: "2023-06-16T18:49:14Z"
  name: configmaptest
  namespace: default
  resourceVersion: "1507"
  uid: 55234e6f-4cf3-4ef1-bca1-eaf481e4c0fa
