---
# tasks file for kubeadm-setup

- name: downloads the containerd binaries 
  ansible.builtin.get_url: 
    url: https://github.com/containerd/containerd/releases/download/v1.7.2/containerd-1.7.2-linux-arm64.tar.gz
    dest: /tmp/

- name: extract kubeadm
  ansible.builtin.unarchive:
    src: /tmp/containerd-1.7.2-linux-arm64.tar.gz
    dest: /usr/local/
    remote_src: yes

- name: download and install containerd service
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
    dest: /etc/systemd/system/


- name: enable containerd.service
  ansible.builtin.systemd:
    name: containerd.service
    enabled: true   
    daemon_reload: true

- name: download runc
  ansible.builtin.get_url:
    url: https://github.com/opencontainers/runc/releases/download/v1.1.7/runc.arm64
    dest: /usr/local/sbin/
    mode: '0755'

- name: install runc
  ansible.builtin.shell: 
    cmd: install -m 755 runc.arm64 /usr/local/sbin/runc
    chdir: /usr/local/sbin/

- name: download cni plugins
  ansible.builtin.get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v1.3.0/cni-plugins-linux-arm-v1.3.0.tgz
    dest: /tmp/cni-plugins-linux-arm-v1.3.0.tgz


- name: make directory for cni plugins
  ansible.builtin.file:
    path: /opt/cni/bin
    state: directory
  

- name: install cni plugins
  ansible.builtin.unarchive:
    src: /tmp/cni-plugins-linux-arm-v1.3.0.tgz
    dest: /opt/cni/bin/
    remote_src: true 



- name: apt setup for kubeadmin
  ansible.builtin.shell: 
    cmd: apt-get update && apt-get install -y apt-transport-https ca-certificates curl

- name: apt cert setup for kubeadmin
 ansible.builtin.shell:
   cmd: curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg

- name: apt repot setup for kubeadmin
 ansible.builtin.shell:
   cmd: echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list


- name: installes kubelet packages 
  ansible.builtin.shell:
    cmd: sudo apt-get update && sudo apt-get install -y kubelet kubeadm kubectl && sudo apt-mark hold kubelet kubeadm kubectl



